### ISSUE TITLE
Question about Gerber/PCB

### ISSUE THREAD

**Issue by mwedmark** [Sgw32/UltiSID#1]
Hello,

Are you ready to release PCB/Gerbers for this project? What is the current state of the project? How is thefunction compared to SwinSID? Are there any low-hanging fruit to upgrade this? Are there any reason for this 128Mhz project to be any worse than a 16Mhz MEGA emulator?

**Comment by Lalarian** [comment]
Sadly it seems the author is no longer active. You can find some information here: https://www.forum64.de/index.php?thread/113715-ultisid-new-stm32-sid-chip-replacement/

**Comment by Sgw32** [comment]
Hi. No, I'm here :) 
Project is just suspended because I have a lot of other tasks, related to other projects. If you have something to contribute - welcome. 
Current state is that it works with minor glitches in most of tunes. I need to fix it somehow, by using STM32F405 or something else. I just do not see open-source interest to this project from community, and I do not have a in-depth knowledge of STM32. Anyway, the best solution is probably to use Kung Fu Flash to debug this project. And use its address/data code to continue working on it. I may return to this, but first I need to finish some of my crowdfunding projects, related to Amiga and related to retro cars topic. 
Anyway, stay tuned and good luck!

I also can release PCB and Gerbers since they will be heavily modified and they have issues that need to be fixed first. 

Where is 16 MHz MEGA emulator? sounds interesting. 
However, using 128 MHz is only because it latency of getting Address/Data bus is very-very high in comparison to even AVR. So, we need to do it much faster. Here it even uses a buffer of commands -which should not be here, because it's not a true realtime solution. 

Also I can pay money if someone can achieve results on this project/ finally release it.

**Comment by mwedmark** [comment]
Thanks for you prompt answer! Yea I just happen to have a good amount of Kung Fu Flashes (built some) so thanks for that idea. Sorry to see low interest, think it is a great idea to leave MEGAAVR for this newer tech. (What I've meant with MEGA emulator was really SwinSID.. I think it actually uses 32Mhz). 

One idea of mine would be to team up with/cross-breed with this project: https://codeberg.org/CBMretro/PicoSID
Resonable starting-point for a HW RP2040-based SID. Currently without software which you seem to have here! :-) Maybe the usage of PIO's/DMA would make the latecy much less prominent. Would there be any reason for that HW-platform being worse that what you have here? Pity it is not in SID-format but bigger. I could probably be optimized into a double-sided PCB with components place on both sides. Tried it briefly but doubled the production cost...

**Comment by Sgw32** [comment]
Hi everyone. Hardware published. Please do not order it until address lines are connected properly. But it is enough to use it as a reference.
